spring.application.name=ZeotapDataIngestion

spring.datasource.driver-class-name=com.clickhouse.jdbc.ClickHouseDriver
spring.datasource.url=jdbc:clickhouse://localhost:8123/uk?compress=0
spring.datasource.username=gayathri
spring.datasource.password=gayathri
spring.datasource.initialization-mode=never

clickhouse.host=localhost
clickhouse.port=8123
clickhouse.database=uk
clickhouse.jwt-token=

spring.web.client.http-client=none


server.port=8080
